import type { PageConfig, PageProfile, PageTheme } from "./types";

export const defaultTheme: PageTheme = {
  background: "#ffffff",
  foreground: "#000000",
  card: "#121313",
  accent: "#ade0ff",
  radius: "round",
  shadow: "soft",
};

export const defaultProfile: PageProfile = {
  name: "Username",
  bio: "Short bio for your personal homepage.",
  location: "Location",
  avatarUrl: "",
  contacts: [
    { label: "Email", href: "mailto:email@example.com" },
    { label: "Website", href: "https://example.com" },
  ],
};

export const defaultPageConfig: PageConfig = {
  username: "username",
  title: "Username - Link Tree",
  description: "A static 3D bento personal homepage inspired by soft social link cards.",
  profile: defaultProfile,
  theme: defaultTheme,
  updatedAt: "2026-05-21T00:00:00.000Z",
  layout: [
    { i: "social-twitter", x: 0, y: 0, w: 2, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-medium", x: 2, y: 0, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-pinterest", x: 3, y: 0, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-coffee", x: 0, y: 1, w: 2, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-figma", x: 2, y: 1, w: 1, h: 2, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-discord", x: 3, y: 1, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-linkedin", x: 0, y: 2, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-gumroad", x: 1, y: 2, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-dribbble", x: 3, y: 2, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-stack", x: 0, y: 3, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-instagram", x: 1, y: 3, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
    { i: "social-reddit", x: 2, y: 3, w: 1, h: 1, minW: 1, minH: 1, maxW: 2, maxH: 2 },
  ],
  widgets: [
    {
      id: "social-twitter",
      type: "link",
      props: {
        title: "Twitter",
        href: "https://twitter.com/",
        description: "@username",
        logo: { type: "builtin", key: "x" },
        color: "#f5f5f5",
        background: { type: "gradient", from: "#2f2f2f", to: "#101112", angle: 180 },
      },
    },
    {
      id: "social-medium",
      type: "link",
      props: {
        title: "Medium",
        href: "https://medium.com/",
        description: "@username",
        logo: { type: "builtin", key: "medium" },
        color: "#1c1c1c",
        background: { type: "solid", value: "#f7f7f2" },
      },
    },
    {
      id: "social-pinterest",
      type: "link",
      props: {
        title: "Pinterest",
        href: "https://pinterest.com/",
        description: "@username",
        logo: { type: "builtin", key: "pinterest" },
        color: "#E60023",
        background: { type: "solid", value: "#ffe8ee" },
      },
    },
    {
      id: "social-coffee",
      type: "link",
      props: {
        title: "Buy me a Coffee",
        href: "https://example.com",
        description: "@username",
        logo: { type: "builtin", key: "coffee" },
        color: "#8b5b05",
        background: { type: "gradient", from: "#ffe181", to: "#f5b63d", angle: 180 },
      },
    },
    {
      id: "social-figma",
      type: "link",
      props: {
        title: "Figma",
        href: "https://figma.com/",
        description: "@username",
        logo: { type: "builtin", key: "figma" },
        color: "#7b38d8",
        background: { type: "gradient", from: "#fce3fe", to: "#bd83e5", angle: 180 },
      },
    },
    {
      id: "social-discord",
      type: "link",
      props: {
        title: "Discord",
        href: "https://discord.com/",
        description: "@username",
        logo: { type: "builtin", key: "discord" },
        color: "#5865F2",
        background: { type: "solid", value: "#dde2ff" },
      },
    },
    {
      id: "social-dribbble",
      type: "link",
      props: {
        title: "Dribbble",
        href: "https://dribbble.com/",
        description: "@username",
        logo: { type: "builtin", key: "dribbble" },
        color: "#EA4C89",
        background: { type: "gradient", from: "#ff95d3", to: "#ef64bd", angle: 180 },
      },
    },
    {
      id: "social-linkedin",
      type: "link",
      props: {
        title: "LinkedIn",
        href: "https://www.linkedin.com/",
        description: "@username",
        logo: { type: "builtin", key: "linkedin" },
        color: "#0A66C2",
        background: { type: "solid", value: "#dff0ff" },
      },
    },
    {
      id: "social-gumroad",
      type: "link",
      props: {
        title: "Gumroad",
        href: "https://gumroad.com/",
        description: "@username",
        logo: { type: "builtin", key: "gumroad" },
        color: "#ff90e8",
        background: { type: "solid", value: "#232323" },
      },
    },
    {
      id: "social-stack",
      type: "link",
      props: {
        title: "Stack",
        href: "https://stackoverflow.com/",
        description: "@username",
        logo: { type: "builtin", key: "stack" },
        color: "#f48024",
        background: { type: "solid", value: "#fff1df" },
      },
    },
    {
      id: "social-instagram",
      type: "link",
      props: {
        title: "Instagram",
        href: "https://instagram.com/",
        description: "@username",
        logo: { type: "builtin", key: "instagram" },
        color: "#e1306c",
        background: { type: "gradient", from: "#ffe0f1", to: "#ffd39a", angle: 145 },
      },
    },
    {
      id: "social-reddit",
      type: "link",
      props: {
        title: "Reddit",
        href: "https://reddit.com/",
        description: "@username",
        logo: { type: "builtin", key: "reddit" },
        color: "#ff4500",
        background: { type: "solid", value: "#ffe4d8" },
      },
    },
  ],
};
