services:
  mellow-grid:
    build: .
    ports:
      - "3000:3000"
    environment:
      MELLOWGRID_MODE: file
      MELLOWGRID_DEFAULT_USER: hanam
      MELLOWGRID_DATA_DIR: /app/data
      MELLOWGRID_EDITOR_PASSWORD: ""
    volumes:
      - ./data:/app/data
